### ISSUE TITLE
Crash with Embeddium

### ISSUE THREAD

**Issue by marlester-dev** [txnimc/SodiumOptionsAPI#10]
Embeddium is incompatible with Reeses Sodium Options.
SodiumOptionsAPI requires Reeses Sodium Options.
1.0.5.
No crash on 1.0.2

**Comment by nthxny** [comment]
Are you using Embeddium on NeoForge?

**Comment by nthxny** [comment]
Why are you using Embeddium on Fabric?

**Comment by nthxny** [comment]
It doesn't. It is a fork of Sodium and will run the same.

Please install the correct dependencies listed on the mod page before leaving issues
