### ISSUE TITLE
Crashing when clicking Video Settings

### ISSUE THREAD

**Issue by StoneLegion** [txnimc/SodiumOptionsAPI#13]
![image](https://github.com/user-attachments/assets/1d2c7a92-be5a-4757-8e5c-fe254de15bf9)

It's crashing when I enable your API, if I keep yours disabled it's fine including reeses being enabled.

**Comment by StoneLegion** [comment]
n/m I think it's my fault. Not sure why Reese's is .3 when I have it only set to .1....

**Comment by Cinderheart** [comment]
I'm not so sure, I'm having issues too.

**Comment by Ciellix** [comment]
> n/m I think it's my fault. Not sure why Reese's is .3 when I have it only set to .1....

that version supports supports 1.21.1 - 1.21.3 or so it says on curseforge

![asdasdasd](https://github.com/user-attachments/assets/5d52ba73-479a-4682-aa4f-914db9b92959)
