### ISSUE TITLE
SodiumOptionsAPI it crashes with the latest version of Sodium & Reese Sodium Options in 1.21.1

### ISSUE THREAD

**Issue by raspberrygitq** [txnimc/SodiumOptionsAPI#15]
### Logs
https://mclo.gs/4G69t2i
### It refers to
#13

**Comment by VaporeonScripts** [comment]
same error:
https://mclo.gs/UwRRMbl

**Comment by Crazyminer34** [comment]
same error from me

**Comment by Ciellix** [comment]
same things happening too me. https://mclo.gs/HS6gUEy

**Comment by nthxny** [comment]
should be fixed in latest release
