### ISSUE TITLE
Crash when clicking Video Settings

### ISSUE THREAD

**Issue by BronsonCarder** [txnimc/SodiumOptionsAPI#7]
At first I thought this was related to Reese's Sodium Options. Then I thought it was Sodium/Embeddium Dynamic Lights. But it appears that there is some incompatibility issue, because having Sodium Options API installed causes my game to crash whenever I click on video settings. 
I currently have Dynamic Lights and More Culling installed. Both display their menus just fine without Reese's or the OptionsAPI.

**Comment by nthxny** [comment]
Should be fixed now with latest release.

**Comment by BronsonCarder** [comment]
Can confirm, seems to be working now.

**Comment by BronsonCarder** [comment]
Well, no. Actually, now that I've updated it's saying it requires Reese's Sodium Options. Which I do have installed.

**Comment by nthxny** [comment]
Fixed again. Apparently the mod ID is different on Fabric for some reason.

**Comment by BronsonCarder** [comment]
Awesome, thanks for the quick fix!

That is weird though... I thought I had updated, but I was still using the old version... but it did work that time for some reason. lmfao
Oh well, it should work now, that's all that matters. lol
