### ISSUE TITLE
SodiumOptionsAPI 1.0.4 (Fabric) does not start when Reese Sodium Options is present.

### ISSUE THREAD

**Issue by raspberrygitq** [txnimc/SodiumOptionsAPI#9]
Hi, I come here with the problem of incompatibility of this modification with Reese Sodium Options. The game crashes in that it requires Reese Sodium Options to install, where I have it installed. Is this an error on your mod side or on the Reese Sodium Options mod side? 

Rolling back to a previous version of the mod solves the problem.

![image](https://github.com/user-attachments/assets/75048cf8-1a68-4a33-99d3-dc66d1a79a30)

### Logs

https://mclo.gs/Ih0wboP

**Comment by nthxny** [comment]
just fixed this
